# Generated by Django 5.1.6 on 2025-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
